/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hollyit.drupaldevel.wizards.theme;

import java.util.ArrayList;
import javax.swing.JPanel;
import org.hollyit.drupaldevel.DrupalDevelTool;
import org.hollyit.drupaldevel.wizards.WizardUtils;
import org.openide.util.NbPreferences;

public final class ThemeWizardVisualPanel1 extends JPanel {

    /** Creates new form ThemeWizardVisualPanel1 */
    public ThemeWizardVisualPanel1() {
        initComponents();
        setVersions();        
    }

    @Override
    public String getName() {
        return "Drupal Version";
    }

    private void setVersions() {
        ArrayList items = WizardUtils.getMajorVersions("theme");
        String drVer = NbPreferences.forModule(DrupalDevelTool.class).get("drupalVersion", "");
        this.cbDrupalVersion.removeAllItems();
        for (int i = 0; i < items.size(); i++) {
            String item = items.get(i).toString();
            Object obj = makeObj(item);
            cbDrupalVersion.addItem(obj);
            if (obj.toString().equals(drVer)) {
                cbDrupalVersion.setSelectedItem(obj);
            }
        }
    }

    private Object makeObj(final String item) {
        return new Object() {

            @Override
            public String toString() {
                return item;
            }
        };
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbDrupalVersion = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        cbDrupalVersion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ThemeWizardVisualPanel1.class, "ThemeWizardVisualPanel1.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(cbDrupalVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbDrupalVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cbDrupalVersion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
