/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package org.netbeans.modules.php.drupaldevel.ui.customizer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.netbeans.modules.php.drupaldevel.Util;
import org.netbeans.modules.php.drupaldevel.libraryParser;
import org.netbeans.modules.php.api.phpmodule.PhpModule;
import org.netbeans.modules.php.drupaldevel.DrupalDevelPreferences;
import org.netbeans.spi.project.ui.support.ProjectCustomizer.Category;

/**
 *
 * @author Jamie Holly <jamie@hollyit.net>
 */
public class DrupalCustomizerPanel extends javax.swing.JPanel {

    private final Category category;
    private final PhpModule phpModule;

    DrupalCustomizerPanel(Category category, PhpModule phpModule) {
        assert category != null;
        assert phpModule != null;

        this.category = category;
        this.phpModule = phpModule;

        this.category.setStoreListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                storeData();
            }
        });

        initComponents();


        drupalLibraryPathTextField.setText(DrupalDevelPreferences.getLibraryPath(phpModule));
        if (getLibraryPath().equals(DrupalDevelPreferences.getDefaultLibraryPath())) {
            drupalLibraryPathTextField.setText("");
        }
        drupalLibraryPathTextField.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                validateLibraryPath();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validateLibraryPath();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validateLibraryPath();
            }
        });

        validateLibraryPath();
        // validateData();
    }

    private Boolean validateLibraryPath() {
        if (drupalLibraryPathTextField.getText().equals("")) {
            lblInvalid.setVisible(false);
            updateDrupalVersions();
            return true;
        }
        Boolean pathGood = DrupalDevelPreferences.validateLibraryPath(drupalLibraryPathTextField.getText().toString());
        if (pathGood) {
            lblInvalid.setVisible(false);
            updateDrupalVersions();
        } else {
            lblInvalid.setVisible(true);
        }
        return pathGood;
    }

    private void updateDrupalVersions() {
        this.cbDrupalVersion.removeAllItems();
        String drVer = DrupalDevelPreferences.getDrupalVersion(phpModule);
        if (drVer.equals("")) {
            drVer = DrupalDevelPreferences.getDefaultDrupalVersion();
        }
        String path = drupalLibraryPathTextField.getText().toString();

        if (path.equals("")) {
            path = DrupalDevelPreferences.getLibraryPath(phpModule);
        }
        path = path + "/code";

        ArrayList items = libraryParser.parseTree(path);
        cbDrupalVersion.addItem("Default");
        for (int i = 0; i < items.size(); i++) {
            String item = items.get(i).toString();
            Object obj = Util.makeObj(item);
            cbDrupalVersion.addItem(obj);
            if (item.toString().equals(drVer)) {
                cbDrupalVersion.setSelectedItem(obj);
            }
        }

    }

    void storeData() {
        if (getLibraryPath().equals(DrupalDevelPreferences.getDefaultLibraryPath())) {
            drupalLibraryPathTextField.setText("");
        }
        DrupalDevelPreferences.setDrupalVersion(phpModule, getDrupalVersion());
        DrupalDevelPreferences.setLibraryPath(phpModule, getLibraryPath());
    }

    private String getLibraryPath() {
        return drupalLibraryPathTextField.getText().toString();
    }

    private String getDrupalVersion() {
        return cbDrupalVersion.getSelectedItem().toString();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbDrupalVersion = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        drupalLibraryPathTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblInvalid = new javax.swing.JLabel();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DrupalCustomizerPanel.class, "DrupalCustomizerPanel.jLabel1.text")); // NOI18N

        cbDrupalVersion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DrupalCustomizerPanel.class, "DrupalCustomizerPanel.jLabel2.text")); // NOI18N

        drupalLibraryPathTextField.setText(org.openide.util.NbBundle.getMessage(DrupalCustomizerPanel.class, "DrupalCustomizerPanel.drupalLibraryPathTextField.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(DrupalCustomizerPanel.class, "DrupalCustomizerPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(DrupalCustomizerPanel.class, "DrupalCustomizerPanel.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblInvalid.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        lblInvalid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/php/drupaldevel/wizards/dialog-warning.png"))); // NOI18N
        lblInvalid.setText(org.openide.util.NbBundle.getMessage(DrupalCustomizerPanel.class, "DrupalCustomizerPanel.lblInvalid.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(drupalLibraryPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(lblInvalid))
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drupalLibraryPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDrupalVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbDrupalVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Util.browseDrupalLibraryPath(this, drupalLibraryPathTextField);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                           
        drupalLibraryPathTextField.setText(DrupalDevelPreferences.libraryInstallPath());
        if (!validateLibraryPath()){
         JOptionPane.showMessageDialog(null, 
                                        "Could not locate the default library files at " + DrupalDevelPreferences.libraryInstallPath()+ ". Try reinstalling the module.",
                                        "Error",
                                        JOptionPane.ERROR_MESSAGE);   
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbDrupalVersion;
    private javax.swing.JTextField drupalLibraryPathTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInvalid;
    // End of variables declaration//GEN-END:variables
}
